version: '3.5'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=sdr
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: pg_isready -U postgres
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
